### PR TITLE
[WIP] Feature/validation

### PR DESCRIPTION
**Pull request by jaapio**
Validation setup.

### CODE REVIEW

**Comment by jaapio** [comment]
@mvriel I create this pr as a discussion about the implementation of #1599.
Since I based the code on an other pr you didn't merge yet it is a bit messy. But all interesting code is in commit  9543579.

I suggest that we introduce an interface for file in phpdocumentor/Reflection. So we can create a decorator like plugin structure. Each middleware can add it's own result to the file object as a wrapper around this file. Which allows other classes to process the results. E.g. a view can get all messages from a file and render those. Same would apply to a console logger which logs the validation messages to the console.

A down side is that the classes using the specialized decorators will have to check if the specialized methods are available. Since this might change when middlewares are disabled.

I would like to hear what you are thinking about this setup.

**Comment by mvriel** [comment]
@jaapio I foresee maintenance issues with using specialized versions of the File class since you would need to specifically check in a view which sort of File you have. This also only works when you have a single decorator because nesting this trick several times breaks aforementioned checks.

I suggest creating a new Collection object (i.e. `Violations`) that is instantiated in the DIC and provided to the validator. This Violations collected can then be populated with the discovered validation violations and a view that wants to read the violations can then have the Violations Collection object injected and use that to process all issues.

This have a few advantages:

- The File Value Object is consistent and thus every class using this Value Object knows what it can expect
- We can use the Violations collection also to record violations in other files, such as the menu.xml Menu Definition (Markdown parsing) or Markdown/ReST files. 
- There is less coupling between the Reflection library and the Validation library

**Comment by jaapio** [comment]
Lets see how that will work out. It feels a bit strange to inject an object and modify that with other classes.  It would have been nice if we could make the violations collection immutable. But at the moment I don't have a better solution. I think this is more or less the issue of doing these kind of things in middlewares. 

Even when we move the validation to a step after the parsing process the voilations have to be stored in the DI-container. Otherwise the view doesn't have access to it. Or we should find a way to add those violations to the project. But that will result in the same issues as you are seeing with the file class.

**Comment by mvriel** [comment]
An alternative may be to have a ViolationsRepository that is responsible for persisting and retrieving violations (for example in cache or memory). That may be a more stable approach as that is an immutable object?

**Comment by jaapio** [comment]
I will try the approach with the collection first. Basicly that will do the same as a repository would do. Using the cache for temporary storage doesn't feel right either. Cache should be disposable at any time, from my point of view. In this case that will cause a datalost.

**Comment by mvriel** [comment]
Closing this PR as it is superseded by https://github.com/phpDocumentor/phpDocumentor2/pull/1721

**Pull request closed without merging**
