### PR TITLE
gitattributes: do not export tests [closes #1529]

### LINKED ISSUE #1529: Composer installation fails in folders with long names
If I try to install phpDocumentor 2.8.2 in a folder with a long name, the Composer install fails:

    [ErrorException]
    ZipArchive::extractTo(): Full extraction path exceed MAXPATHLEN (260)

That already happens for `c:\test\a-long-folder-name\a-long-folder-name\composer.json`. It seems that the problem is caused by the files in vendor\phpdocumentor\phpdocumentor\features; not sure, if they should be there at all.

### PR DESCRIPTION
**Pull request by TomasVotruba**
Tests are not needed by composer.

### CODE REVIEW

**Comment by mvriel** [comment]
Hi @TomasVotruba, thanks for this PR! Do you think you can exclude the `features` folder folder as well? That's the one with the huge file names because of the Behat features. Thank you!

**Comment by TomasVotruba** [comment]
@mvriel Sure. While we're at it, all these are not used by composer, so I'd exclude them as well:

- /ansible
- /docs
- /features
- /tests
- .gitattributes
- .gitignore	
- .scrutinizer.yml
- .travis.yml
- CHANGELOG.md	
- CONTRIBUTING.md
- README.md
- VERSION
- Vagrantfile
- behat.yml
- box.json
- build.xml
- composer.json
- composer.lock
- package.xml
- phpdoc.dist.xml
- phpmd.xml.dist
- phpunit.xml.dist
- wercker.yml

**Comment by mvriel** [comment]
IIRC is .gitattributes and .gitignore used by composer because composer does git clones when you prefer-source it; the VERSION file is required for the correct functioning of phpDocumentor; I also don't know how composer will react when the composer.json and lock file are excluded in this way

**Comment by mvriel** [comment]
The rest does indeed look redundant for a composer installation

**Comment by TomasVotruba** [comment]
Sorry, I forgot to remove composer.* while copying.  
`.gitattributes` and `.gitignore` can be left out with no problem. I'm using it in many repo, [Doctrine](https://github.com/doctrine/doctrine2/blob/900b55d16afdcdeb5100d435a7166d3a425b9873/.gitattributes#L3-L4) too etc.

I've updated the list

**Comment by mvriel** [comment]
Looks like a perfect list :+1:

**Comment by TomasVotruba** [comment]
It's up!

**Comment by mvriel** [comment]
:+1:

**Comment by mvriel** [comment]
This commit needs to be cherry-picked to the master branch as well because that is where the phpDocumentor 2.8.* release is (develop is phpDocumentor 3); I can do that tomorrow (I am in the midst of a refactoring that I'd rather not stash now :) )

**Comment by TomasVotruba** [comment]
:+1:

**Comment by ross-p** [comment]
@mvriel Any update on this?  I'm having this problem on Win 8.1 x64 on a phpdoc 2.8.2 that I pulled today.  Thanks  :)

**Comment by mvriel** [comment]
Apparently this task slipped my mind; I have just cherry-picked this to master and tagged 2.8.3

**Pull request merged**
