### PR TITLE
Inserted inheriteddoc tag into tags list

### PR DESCRIPTION
**Pull request by ddymko**
Looking through documentation issue, I found issue 955. I copied over the information about inheritdoc over to tags.rst

### CODE REVIEW

**Comment by mvriel** [comment]
Hello @ddymko,

My apologies for not responding sooner to your PR. I have review this side-by-side with the changes in PSR-5 that I have in draft currently before I feel comfortable with merging it. This takes some time (especially as I am limited in time and have several things going on at the same time). Please accept my apologies for the lateness and I hope to be able to resolve this as soon as possible.

**Comment by ddymko** [comment]
No worries! Let me know if anything needs to be changed

**Comment by mvriel** [comment]
Thank you for your submission; I apologize for the delay in merging it but life kinda got in the way (still does alas) but nonetheless: it is merged :)

**Comment by kaldari** [comment]
The documentation has said for a few years that "we are working to include a new (normal) tag in the PHPDoc Standard ``@inheritDoc``". Is there any update on that or online discussion that we can follow?

**Comment by jaapio** [comment]
Could you please open a new issue. This pr is closed. And it will be hard to track this way. 
Thanks!

**Pull request merged**
