### PR TITLE
moved phpDocumentor/Command to phpDocumentor/Application/Cli/Command

### PR DESCRIPTION
**Pull request by rgeraads**
Tests are still pending!

### CODE REVIEW

**Comment by jaapio** [comment]
Could you please check the scrutinizer issues you introduced. Looks like 4 style issues.

**Comment by rgeraads** [comment]
fixed 3 style issues. the 1 remaining is 12 month old report of a bug. I checked, and I think it was already fixed some time.

**Comment by jaapio** [comment]
tnx!

**Comment by mvriel** [comment]
No comments! Thank you, thid brings us one step closer to having a clean model

**Pull request merged**
