### PR TITLE
Add unit tests for the Descriptor namespace

### PR DESCRIPTION
**Pull request by mvriel**
In this commit I have also performed a few cleanups in the descriptor classes.
This can mean that other parts of the code have been touched as well.

TODO:

- [ ] Add more tests for the ProjectDescriptorBuilder
- [ ] Add tests in child classes for all Abstract base classes (where missing)
- [ ] Add tests for the incomplete test cases for all Descriptors
- [ ] Add tests for the ProjectDescriptor
- [ ] Add tests for the Cache namespace
- [ ] Add tests for the Builder namespace

### CODE REVIEW

**Comment by jaapio** [comment]
Please update your branch with develop. This will make all build phases pass.

**Comment by mvriel** [comment]
Rebased against develop

**Comment by jaapio** [comment]
Can we merge this?

**Comment by mvriel** [comment]
Done :D

**Pull request merged**
