### PR TITLE
upgrade to PHP CodeSniffer 2 and fix PSR-2

### PR DESCRIPTION
**Pull request by fdewinne**
I updated composer dependencies to PHP CodeSniffer 2 (minimum required by continuousphp) and added the phpcs.xml manifest file. Once done, I fixed the errors found by phpcs.

You can have a look at https://continuousphp.com/git-hub/fdewinne/phpDocumentor2/build/24410629-7c79-441f-8213-022cbf19ea2d/output for more details

### CODE REVIEW

**Comment by fdewinne** [comment]
In my fork, I've set "src" and "tests/unit" as folder to test. Not sure it's required to check "tests/data" and "tests/ReferenceImplementation.php"

**Comment by jaapio** [comment]
Thanks @fdewinne! 

@mvriel this one can be merged without any issues.

**Comment by mvriel** [comment]
Thanks @fdewinne for your contribution and thanks @jaapio for the review :)

**Comment by fdewinne** [comment]
You are welcome guys ;)

**Comment by fdewinne** [comment]
By the way, don't forget to update your phpcs settings in continuousphp by replacing the "test" folder into "tests/unit" and your phpcs result will be green ;)

**Pull request merged**
